parameters:
    mode: development
    orm.db:
        driver: pdo_mysql
        host: 127.0.0.1
        port: 3306
        user: backend_test
        password: backend_test
        dbname: backend_test
        charset: utf8mb4
        collation: utf8mb4_unicode_ci
    orm.paths: ['../../mappings/']
services:
    _defaults:
        autowire: true
        autoconfigure: true
    Doctrine\ORM\EntityManager:
        factory: 'Samknows\Factory\Doctrine\EntityManagerFactory::createEntityManager'
        arguments: ['%orm.db%', '%orm.paths%', '%mode%']
        public: false
    entity_manager: '@Doctrine\ORM\EntityManager'
    Samknows\Command\AggregateCommand:
        tags:
            - { name: 'console.command', command: 'samknows:aggregate' }
    Samknows\Command\LoadDataCommand:
        tags:
            - { name: 'console.command', command: 'samknows:loaddata' }
    Samknows\Command\SearchCommand:
        tags:
            - { name: 'console.command', command: 'samknows:search' }
    Samknows\Model\SearchModel:
        tags:
            - { name: 'application.model', command: 'search' }
    Samknows\Model\LoadDataModel:
        tags:
            - { name: 'application.model', command: 'loaddata' }
    Samknows\Model\AggregateModel:
        tags:
            - { name: 'application.model', model: 'aggregate' }