<?php

namespace Samknows\Tests\Command;

use Samknows\Command\LoadDataCommand;
use Samknows\Tests\Setup\CommadTestCase;
use Symfony\Component\Console\Tester\CommandTester;

final class LoadDataCommandTest extends CommadTestCase
{

    public function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCanBeCreated(): void
    {
        $container = $this->getContainer();
        $this->assertEquals(LoadDataCommand::class, get_class($container->get(LoadDataCommand::class)));
    }

    public function testCanBeNamed()
    {
        $container = $this->getContainer();
        /* @var $loadDataCommand LoadDataCommand */
        $loadDataCommand = $container->get(LoadDataCommand::class);
        $this->assertEquals('app:load-data', $loadDataCommand->getName());
    }

    public function testCanBeCreatedWithArguments()
    {
        $container = $this->getContainer();
        /* @var $loadDataCommand LoadDataCommand */
        $loadDataCommand = $container->get(LoadDataCommand::class);
        $this->assertGreaterThanOrEqual(1, $loadDataCommand->getDefinition()->getArgumentCount());
    }

    public function testCanBeCreatedWithDescription()
    {
        $container = $this->getContainer();
        /* @var $loadDataCommand LoadDataCommand */
        $loadDataCommand = $container->get(LoadDataCommand::class);
        $this->assertRegExp('/[\w\s\.]{8,}/', $loadDataCommand->getDescription());
    }

    public function testExecute()
    {
        $container = $this->getContainer();
        /* @var $loadDataCommand LoadDataCommand */
        $loadDataCommand = $container->get(LoadDataCommand::class);
        $application = $this->getApplication();
        $command = $application->find($loadDataCommand->getName());

        $commandTester = new CommandTester($command);
        $commandTester->execute([
            'command'  => $command->getName(),
            'data-file' => 'data/test-data-tiny.json',
        ]);

        $output = $commandTester->getDisplay();
        $this->assertContains('Data loaded', $output);
    }

}